### ISSUE TITLE
Group description

### ISSUE THREAD

**Issue by rlanvin** [apeisa/UserGroups#31]
In the project I'm working on, there is a lot of groups that have meaningless names (e.g. a number, or an alphanumeric code). I think I'll need to add a new field "group description" in addition to the title, where the admin can write a quick explanation. I can do that as a completely separate fork of the module for this project only, but I think it could be a nice feature that would benefit to everybody. What do you think?

**Comment by teppokoivula** [comment]
Editing group descriptions (and names) is currently implemented in the [feature-edit-group-details](https://github.com/apeisa/UserGroups/tree/feature-edit-group-details) branch. Unless someone has a reason why this shouldn't be possible, I'm thinking of merging this as soon as I've done some testing.

@apeisa, @rlanvin, @niklaka?

**Comment by apeisa** [comment]
Just skimmed through the code and didn't spotted anything cautious. Nice that you have added some docblocks also!

**Comment by teppokoivula** [comment]
Just merged aforementioned feature. Group titles and descriptions are now editable in the group details view.

Regarding the only open question here, selecting groups with an autocomplete in the access tab, that's definitely possible (and not too complicated), but personally I'd be against it. Mostly because I prefer to see a list of groups, rather than having to remember how I've named them.

Either way, this has very little to do with group details anymore, so to keep things in order, I'm closing this issue. I'd suggest opening a new issue for access tab group select via autocomplete, if it still feels important :)
